site_name: Rory&#39;s Mod
theme: readthedocs
repo_url: https://github.com/GOGO98901/RorysMod/
site_description: A forge mod for Minecraft 1.7.10
site_author: Rory Claasen
copyright: Copyright Rory Claasen (Apache 2.0)
google_analytics: ['UA-45259414-3', 'mkdocs.org']

pages:
    - Home: 'index.md'
    - Installation: 'install.md'
    - Change Log: 'changes.md'
    - Better Sleeping: 'bettersleeping.md'
    - Modular Lasers:
        - Rifle Modules: 'modularlasers/riflemodules.md'
    - License: 'license.md'
    - Developer:
        - Metrics: 'metrics.md'
        - Travis CI: 'buildstatus.md'
